backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "horse"
    identifier_field: "name"
    label: "Pferde"
    folder: "src/pages/pferde"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "horse"}
      - {label: "Seitentitel", name: "siteTitle", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Kurzbeschreibung", name: "description", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Titel neben Bild", name: "headline", widget: "string"}
      - {label: "Untertitel neben Bild", name: "subheadline", widget: "string"}
      - {label: "Beschreibung neben Bild", name: "body", widget: "markdown"}

  - name: "feature"
    identifier_field: "name"
    label: "Leistungen"
    folder: "src/pages/leistungen"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "horse"}
      - {label: "Seitentitel", name: "siteTitle", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Kurzbeschreibung", name: "description", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Titel neben Bild", name: "headline", widget: "string"}
      - {label: "Untertitel neben Bild", name: "subheadline", widget: "string"}
      - {label: "Beschreibung neben Bild", name: "textNextToImage", widget: "markdown"}
      - {label: "Beschreibung neben Bild", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Seiten"
    files:
      - file: "src/pages/index.md"
        label: "Startseite"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: markdown}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
      - file: "src/pages/ueber-mich.md"
        label: "Über mich"
        name: "ueber-mich"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Seitentitel", name: "siteTitle", widget: "string"}
          - {label: "Bild", name: "image", widget: "image"}
          - {label: "Titel neben Bild", name: "headline", widget: "string"}
          - {label: "Untertitel neben Bild", name: "subheadline", widget: "string"}
          - {label: "Beschreibung neben Bild", name: "textNextToImage", widget: "markdown"}
          - {label: "Fließtext", name: "body", widget: "markdown"}
      - file: "src/pages/impressum.md"
        label: "Impressum"
        name: "impressum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "text"}
          - {label: "ID", name: "id", widget: "hidden"}
          - {label: "Seitentitel", name: "siteTitle", widget: "string"}
          - {label: "Fließtext", name: "body", widget: "markdown"}
      - file: "src/pages/datenschutz.md"
        label: "Datenschutzerklärung"
        name: "datenschutz"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "text"}
          - {label: "ID", name: "id", widget: "hidden"}
          - {label: "Seitentitel", name: "siteTitle", widget: "string"}
          - {label: "Fließtext", name: "body", widget: "markdown"}
